betagouv/itou-cocorico

.github/workflows/php_staging.yml

:sparkles: testing fork of clever cloud github deploy

---

.github/workflows/php_prod.yml

:wrench: fixed prod deploy

---

app/config/security.yml
clevercloud/init/parameters.yml
clevercloud/pre_build_hook.sh
doc/clevercloud.md
docker/Dockerfile
docker/parameters.yml
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig

:lipstick: domain configuration and validation, encryption

---

clevercloud/init/parameters.yml
clevercloud/pre_build_hook.sh

:wrench: updating parameters and deploy script to include mailer info

---

app/Resources/translations/cocorico_user.fr.xliff
src/Cocorico/CoreBundle/Admin/ListingCharacteristicAdmin.php
src/Cocorico/CoreBundle/Resources/views/Dashboard/layout.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_nav.html.twig
src/Cocorico/UserBundle/Admin/UserAdmin.php
src/Cocorico/UserBundle/Entity/User.php
src/Cocorico/UserBundle/Form/Type/RegistrationFormType.php
src/Cocorico/UserBundle/Listener/UserRequestListener.php
src/Cocorico/UserBundle/Resources/config/config.yml
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_login.html.twig
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_login_register.html.twig
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig

- Fixed bug in characteristic admin panel, quick fix

:hammer: fixed caracteristics admin page bug

---

app/Resources/translations/cocorico.fr.xliff
app/Resources/translations/cocorico_contact.fr.xliff
app/Resources/translations/cocorico_home.fr.xliff
app/Resources/translations/cocorico_listing.fr.xliff
clevercloud/post_build_hook.sh
composer.json
composer.lock
src/Cocorico/ContactBundle/Resources/views/Frontend/index.html.twig
src/Cocorico/CoreBundle/Controller/Frontend/HomeController.php
src/Cocorico/CoreBundle/Resources/config/parameters.yml
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_footer.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig
src/Cocorico/PageBundle/Admin/PageAdmin.php
src/Cocorico/PageBundle/Resources/config/admin.yml
src/Cocorico/PageBundle/Resources/views/Frontend/Page/show.html.twig

- nouveaux verbatims
- corrections
- ajout éditeur texte riche pour les pages
- mise en page légère pour les pages "statiques"

[WIP] Introduction verbatims et nouvelles pages

---

app/Resources/translations/cocorico_contact.fr.xliff
src/Cocorico/ContactBundle/Resources/views/Frontend/index.html.twig
src/Cocorico/CoreBundle/Resources/config/parameters.yml
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig
src/Cocorico/CoreBundle/Resources/views/Mails/layout.html.twig

- retrait numéro de téléphone partout
- corrections formulaire de contact

:lipstick: fixing contact form oddities, removing phone number mentions

---

.gitignore
app/Resources/translations/cocorico_user.fr.xliff
app/Resources/translations/validators.fr.xliff
src/Cocorico/UserBundle/Entity/User.php
src/Cocorico/UserBundle/Form/Type/RegistrationFormType.php
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig

Adaptations pour premiers inscrits après open lab
- nouveaux champs utilisateur (siret, naf, ...)
- adaptation du formulaire d'inscription

[WIP] [DB UPDATE] Nouveau formulaire d'inscription

---

app/Resources/translations/cocorico_listing.fr.xliff
docker/Dockerfile
docker/Dockerfile_Full
docker/database.sql
docker/docker_full_init.sh

Docker Script  updates

---

app/Resources/translations/SonataUserBundle.fr.xliff
src/Cocorico/CoreBundle/Admin/ListingAdmin.php
src/Cocorico/UserBundle/Admin/UserAdmin.php

Fix interface admin, plus pratique au quotidien : 
- utilisateurs
- annonces

Admin fixes

---

src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig
web/css/itou.css

:rotating_light: fix checkbox css click

---

app/Resources/translations/SonataUserBundle.en.xliff
app/Resources/translations/SonataUserBundle.fr.xliff
src/Cocorico/UserBundle/Admin/UserAdmin.php
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_modal.html.twig

- nouvelle colonne dans l'interface admin

:hammer: updating admin list columns

---

src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/_listing_show_characteristics.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/show.html.twig
web/css/itou.css

:art: css updates post-deploy

---

src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_nav.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/show.html.twig
src/Cocorico/UserBundle/Entity/User.php
src/Cocorico/UserBundle/Listener/UserRequestListener.php
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig

Retrait de la possibilité de passer de fournisseur à acheteur

:busts_in_silhouette: removing ability to switch between profiles

---

src/Cocorico/CoreBundle/Resources/views/Dashboard/layout.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_nav.html.twig
src/Cocorico/UserBundle/Entity/User.php

Permettre un user admin de gérer son profil, de se déconnecter

:rotating_light: fix admin login/logout

---

app/Resources/translations/cocorico_user.fr.xliff
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig
src/Cocorico/CoreBundle/Security/Voter/ListingVoter.php
src/Cocorico/UserBundle/Admin/UserAdmin.php
src/Cocorico/UserBundle/Entity/User.php
src/Cocorico/UserBundle/Listener/UserRequestListener.php

- ajout d'un vrai type d'utilisateur "admin"
- possibilité de visualiser des annonces avant leur publication (et à tout moment)
- peut tout tester (nouvelle annonce, demande devis, ...)
- bordereau rouge quand connecté en tant qu'admin

:medal_military: added new user role 'admin', with prerogatives

---

src/Cocorico/UserBundle/Form/Type/ProfileAboutMeFormType.php
src/Cocorico/UserBundle/Listener/UserRequestListener.php
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/edit_about_me.html.twig
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig
web/css/itou.css

- Nouveaux champs dans le dashboard utilisateur

:wrench: updaing user profile dashboard

---

app/Resources/translations/SonataAdminBundle.fr.xliff
composer.lock
src/Cocorico/CoreBundle/Admin/QuoteAdmin.php
src/Cocorico/CoreBundle/Entity/Listing.php
src/Cocorico/CoreBundle/Form/Type/Dashboard/ListingEditDescriptionType.php
src/Cocorico/CoreBundle/Form/Type/Frontend/ListingNewType.php
src/Cocorico/CoreBundle/Model/BaseListing.php
src/Cocorico/CoreBundle/Model/ListingLocationSearchRequest.php
src/Cocorico/CoreBundle/Model/ListingSearchRequest.php
src/Cocorico/CoreBundle/Model/Manager/BaseManager.php
src/Cocorico/CoreBundle/Model/Manager/ListingManager.php
src/Cocorico/CoreBundle/Model/Manager/ListingSearchManager.php
src/Cocorico/CoreBundle/Resources/config/Services/admin.yml

- Application du périmètre d'intervention
- Correction bug dashboard utilisateur
- Nouveau panneau administration des devis

[DB MANUAL UPDATE] Perimeter bug

---

src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/_result_listings.html.twig

- formulaire typeform récolte besoin acheteurs

:hammer: quick link to typeform for buyers

---

CHANGELOG.md
app/Resources/translations/cocorico_listing.fr.xliff
src/Cocorico/CoreBundle/Model/BaseListing.php
src/Cocorico/CoreBundle/Model/Manager/ListingSearchManager.php
src/Cocorico/CoreBundle/Resources/config/parameters.yml
src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/edit_client_images.html.twig
src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/edit_images.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/new.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/show.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Quote/_form_new.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Quote/form_quote.html.twig
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/edit_about_me.html.twig
web/css/itou.css

- correction recherche geo
- wording bouton demande de devis
- suppression glisser-deposer

Misc fixes

---

CHANGELOG.md
composer.json
composer.lock
docker/Dockerfile
src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingDuplicateController.php
src/Cocorico/CoreBundle/Model/Manager/ListingManager.php

- annonce dupliquée désormais à valider

:hammer: fixing listing duplication

---

CHANGELOG.md
src/Cocorico/CoreBundle/Resources/views/Form/fields_category.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/new.html.twig
web/css/itou.css

Fix template HTML nouvelle annonce

:wrench: fixing form display

---

CHANGELOG.md
src/Cocorico/CoreBundle/Listener/ItouTrackingRequestListener.php
src/Cocorico/CoreBundle/Utils/Tracker.php

- Contexte client plus détaillé

:hammer: adding referer and useragent

---

CHANGELOG.md
src/Cocorico/UserBundle/Resources/config/Services/listeners.yml

:rotating_light: Admin session fix

---

src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/js/_itou_tracker_js.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig

- Amélioration tracker JS (moins de pertes)

:wrench: improving JS tracker

---

CHANGELOG.md
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryFilterType.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/edit_categories.html.twig
src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/form_categories_ajax.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_login_register.html.twig
web/css/itou.css
web/js/common.js

:sparkles: testing search form with regions

---

src/Cocorico/CoreBundle/Model/Manager/ListingSearchManager.php
src/Cocorico/CoreBundle/Utils/Tracker.php

:hammer: test city search

---

CHANGELOG.md
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryFilterType.php
src/Cocorico/CoreBundle/Resources/config/parameters.yml
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/js/_geocoding_js.html.twig
src/Cocorico/CoreBundle/Utils/Deps.php
src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig
web/css/itou.css

- Fix Recherche Geo
- Fix responsivite menu déroulant

:hammer: fix responsivité

---

CHANGELOG.md
docker/regen_getters.sh
package.json
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Repository/ListingRepository.php
src/Cocorico/CoreBundle/Resources/config/config.yml
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_listings_carousel.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig
src/Cocorico/UserBundle/Controller/Frontend/ProfileController.php
src/Cocorico/UserBundle/Resources/config/config.yml
src/Cocorico/UserBundle/Resources/views/Frontend/Profile/show.html.twig
web/css/itou.css
web/js/vendors.js
yarn.lock

- Nouvelle page vendeur (profil entreprise)

[DB_UPDATE] Profil vendeurs

---

app/Resources/translations/cocorico_user.fr.xliff
src/Cocorico/UserBundle/Resources/views/Frontend/Profile/show.html.twig

- corrections profil vendeur
- modifs base de données

:pencil2: translation fix

---

CHANGELOG.md
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/UserBundle/Resources/views/Frontend/Profile/show.html.twig

Corrections hotfix diverses
- siret, siren, fin du débat
- coordonnées avec des décimales

[DB_UPDATE] HOTFIX Siret siren, coordonnées

---

CHANGELOG.md
src/Cocorico/CoreBundle/Entity/Directory.php

Ajout données utilisateur admin

[DB Update] Add useradmin mail

---

CHANGELOG.md
app/Resources/translations/cocorico_directory.fr.xliff
src/Cocorico/CoreBundle/Controller/Frontend/DirectoryController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Entity/DirectoryClientImage.php
src/Cocorico/CoreBundle/Entity/DirectoryImage.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

- Migration références client vers db structure
- Migration images (logo) vers db structure
- Ajout donnée périmêtre d'action structure

:wrench: adding moar data!

---

CHANGELOG.md
src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/DirectoryCategoriesAjaxController.php
src/Cocorico/CoreBundle/Controller/Frontend/DirectoryCategoriesController.php
src/Cocorico/CoreBundle/Controller/Frontend/DirectoryController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Form/Handler/Frontend/DirectoryFormHandler.php
src/Cocorico/CoreBundle/Form/Type/Dashboard/DirectoryEditType.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryCategoriesType.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryCheckType.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryType.php
src/Cocorico/CoreBundle/Model/DirectoryCheckRequest.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Resources/config/Services/forms.yml
src/Cocorico/CoreBundle/Resources/config/Services/forms_handlers.yml
src/Cocorico/CoreBundle/Resources/config/services.yml
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_presentation.html.twig
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/index.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/adopt.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/form_categories.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/search.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/new.html.twig
src/Cocorico/UserBundle/Controller/Frontend/RegistrationController.php
src/Cocorico/UserBundle/Entity/User.php
src/Cocorico/UserBundle/Form/Handler/RegistrationFormHandler.php
src/Cocorico/UserBundle/Form/Type/RegistrationFormType.php
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/_nav_side.html.twig
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig
web/css/itou.css

- Fonctionnalité adoption de structure
- Formulaire adoption de structure
- Formulaire spécification de structure
- Modification du parcours inscription pour orienter vers l'adoption de structure

Adoption SIAE

---

CHANGELOG.md
doc/database_views.md
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Controller/Frontend/DirectoryController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Form/Type/Dashboard/DirectoryEditType.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryFilterType.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryType.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_presentation.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/adopt.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig
src/Cocorico/UserBundle/Form/Type/RegistrationFormType.php
src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig

- Nouveau Tracking
- Champ type de prestation amélioré.
Après update DB, réinitialiser le champ :
```sql
update directory set presta_type=null;
```

[DB_UPDATE] Tracking prestatype

---

CHANGELOG.md
composer.json
composer.lock
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryFilterType.php
src/Cocorico/CoreBundle/Listener/ItouTrackingRequestListener.php
src/Cocorico/CoreBundle/Model/DirectorySearchRequest.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/_card.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/CoreBundle/Utils/ZPaginator.php

Ajout périmêtre d'activité dans la liste SIAE

Ajout périmêtre d'activité dans la liste SIAE

---

docker/Dockerfile_Full
docker/Dockerfile_Local
docker/docker_db_init.sh
docker/docker_full_init.sh
docker/run_all.sh
docker/run_local_dockers.sh
docker/setup_local_db.sh

:whale: local docker improvements

---

src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

Ajout clé data sur lien typeform

Fix lien recontact typeform

---

CHANGELOG.md
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Model/DirectoryCheckRequest.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

:hammer: siret_siren fix

---

CHANGELOG.md
app/Resources/views/base.html.twig
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryFilterType.php
src/Cocorico/CoreBundle/Model/DirectorySearchRequest.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
web/css/itou.css

| Q             | A
| ------------- | ---
| Bug fix?      | [ ]
| New feature?  | [ ]
| Tests pass?   | [ ]
| Fixed issues  | #... 
| License       | MIT

remove double common.css & update multiselect styles

---

CHANGELOG.md
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Resources/config/parameters.yml
src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig

- Fix recherche DROM-COM
- Fix google map zoom automatique

Correctif recherche outre-mer

---

CHANGELOG.md
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php

:hammer: adding consurtium data points

---

CHANGELOG.md
web/js/common.js

:rotating_light: JS Bootstrap 4 hotfix

---

src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_footer.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig

Lien page inclusion dans le footer

Lien Page Inclusion

---

CHANGELOG.md
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

:pencil: hide button if no data

---

CHANGELOG.md
src/Cocorico/BreadcrumbBundle/Resources/content/breadcrumbs.yml
src/Cocorico/CoreBundle/Controller/Frontend/DirectoryController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/_card.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/search.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

Corrections diverses (cf changelog)

:wrench: adding breadcrumbs on directory page

---

src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

:rotating_light: hotfix, table join

---

CHANGELOG.md
src/Cocorico/CoreBundle/Controller/Frontend/DirectoryController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/adopt.html.twig
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/edit_about_me.html.twig
web/css/itou.scss

Amélioration des performances de la liste SIAE

[DB_UPDATE] Db index check

---

src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_presentation.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/adopt.html.twig

:pencil: wording description

---

CHANGELOG.md
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Form/Type/Frontend/DirectoryFilterType.php
src/Cocorico/CoreBundle/Model/DirectorySearchRequest.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig

- Correctif formulaire recherche SIAE
- Quickfix téléchargement CSV

Quickfix liste SIAE

---

CHANGELOG.md
src/Cocorico/CoreBundle/Admin/DirectoryAdmin.php
src/Cocorico/CoreBundle/Controller/Frontend/HomeController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Entity/DirectoryLabel.php
src/Cocorico/CoreBundle/Entity/DirectoryOffer.php
src/Cocorico/CoreBundle/Entity/Network.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Resources/config/Services/admin.yml
src/Cocorico/UserBundle/Admin/UserAdmin.php
src/Cocorico/UserBundle/Entity/User.php

- Refactor interface administration : liste structures SIAE
- Refactor interface administration : fiche structures SIAE
- Ajout colonne "à la une" pour structures SIAE
- ...

[DB_UPDATE] updating admin interface, testing fixes

---

CHANGELOG.md
src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/DirectoryController.php
src/Cocorico/CoreBundle/Entity/Directory.php
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/_completion_notice.html.twig
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_presentation.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/dir_siae.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/js/_geocoding_js.html.twig

- Indicateur complétion fiche structure
- Wording recherche "structures interviennent sur"
- Correction modale intrusive

Boost fixes

---

CHANGELOG.md
app/config/config_dev.yml
app/config/config_prod.yml
src/Cocorico/CoreBundle/Form/Handler/Frontend/DirectoryFormHandler.php

- Correctif formulaire structure siae
- Ajout log drain kibana pour test

hotfix & drain

---

CHANGELOG.md
src/Cocorico/CoreBundle/Entity/DirectoryImage.php
src/Cocorico/CoreBundle/Form/Handler/Frontend/DirectoryFormHandler.php
src/Cocorico/CoreBundle/Form/Type/Dashboard/DirectoryEditType.php
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_presentation.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Directory/show.html.twig

- Masquer bouton "être recontacté" si coordonnées présentes
- Champ description structure optionnel
- Correction bug image logo fantôme

Button fix

---

CHANGELOG.md
src/Cocorico/CoreBundle/Admin/DirectoryAdmin.php
src/Cocorico/CoreBundle/Controller/Frontend/CompanyListController.php
src/Cocorico/CoreBundle/Model/Manager/DirectoryManager.php
src/Cocorico/CoreBundle/Repository/DirectoryRepository.php
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_bs4_footer.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_footer.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_itou_footer.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index_itou.html.twig
src/Cocorico/UserBundle/Admin/UserAdmin.php
src/Cocorico/UserBundle/Entity/User.php

- Correction orthographique
- Correction bug nombre résultats, refactor manager répertoire
- Refactor page admin utilisateur (renommage + filtre type utilisateur)
- Ajout lien vers mentions légales ITOU / Plateforme de l'inclusion

Trello fixes

---

CHANGELOG.md
app/Resources/views/itou_base.html.twig
app/config/config.yml
src/Cocorico/CoreBundle/Controller/Dashboard/Asker/QuoteController.php
src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/QuoteController.php
src/Cocorico/CoreBundle/Resources/views/Dashboard/Quote/index.html.twig
src/Cocorico/UserBundle/Form/Type/ProfileAboutMeFormType.php
src/Cocorico/UserBundle/Form/Type/ProfileContactFormType.php
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/_completion_notice.html.twig
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/edit_about_me.html.twig
src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/edit_contact.html.twig
webpack.config.js

- Message déploiement sur l'ancienne fonctionnalité "Demandes de contact"
- Correctif modification données utilisateur
- Correctif champ mot de passe non pré-rempli
- Ajustement du versionnage des assets

Contact update fix

---

CHANGELOG.md
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_offers.html.twig
src/Cocorico/CoreBundle/Resources/views/Dashboard/Directory/edit_presentation.html.twig
src/Cocorico/CoreBundle/Resources/views/Form/fields_category.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_itou_footer.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_itou_header.html.twig
src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index_itou.html.twig

Correction wording dashboard des SIAE

:pencil: wording update
